### ISSUE TITLE
Cycle dependencie when installing mkdocstrings

### ISSUE THREAD

**Issue by victor-mariano-leite** [mkdocstrings/python-legacy#2]
**Describe the bug**
I have a requirements file for documentation dependencies like this:

```
markdown==3.*
mkdocs==1.*
mkdocs-material==7.*
pymdown-extensions==8.*
mkdocstrings[python]==0.*
```

But its generating an error for cyclic dependencies when we install it in a virtualenv and validate it with `pipdeptree`

```
Warning!! Cyclic dependencies found:
* mkdocstrings-python-legacy => mkdocstrings => mkdocstrings-python-legacy
* mkdocstrings => mkdocstrings-python-legacy => mkdocstrings
------------------------------------------------------------------------
```

**To Reproduce**

Create a requirements.txt file with the dependencies defined above.

Create a local virtual environment with `virtualenv venv`, run `source venv/bin/activate` (on Linux) then run `pip install requirements.txt`.

Install pipdevtree (`pip install pipdevtree`).

Run `pipdeptree -l > deps.txt`, see the cyclic dependencies error above.

**Comment by pawamoy** [comment]
Is this an actual error or just a warning? The message suggests it's handled by pipdeptree. Also this was already reported in mkdocstrings/mkdocstrings#376, you'll find useful information there. Closing, feel free to further comment here or in the other issue!

**Comment by pawamoy** [comment]
Forgot to close apparently.
