### ISSUE TITLE
Test suite fails after mkdocstrings is updated to 0.24.0

### ISSUE THREAD

**Issue by tijuca** [mkdocstrings/python-legacy#5]
After `mkdocstrings` was updated in Debian unstable to 0.24.0 the test suite for `mkdocstrings-python (legacy)` is failing.

The log of the latest CI autopkgtest run with `mkdocstrings` 0.24.0 is accessible here:
https://ci.debian.net/data/autopkgtest/testing/amd64/m/mkdocstrings-python-legacy/40213685/log.gz

The test suite was failing previously before the latest version bump of `mkdocstrings` too, that was easy fixable by the adding the missed entry to the dictionary.

```
diff --git a/tests/conftest.py b/tests/conftest.py
index c00189f..8a0d92b 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -31,6 +31,7 @@ def fixture_mkdocs_conf(request, tmp_path):
         request = request._parent_request  # noqa: WPS437
 
     conf_dict = {
+        "config_file_path": ".",
         "site_name": "foo",
         "site_url": "https://example.org/",
         "site_dir": str(tmp_path),
```

The CI system is currently using:
- Debian unstable
- Python 3.11
- `mkdocstrings-python (legacy)` version: 0.2.3
- `mkdocstrings` version: 0.24.0

My guess is that after the changes to `mkdocstrings` the test suite for `mkdocstrings-python (legacy)` needs too some adjustments.

**Comment by pawamoy** [comment]
Hi, thanks for the report! You are right, the tests suite needs fixing. I'll apply the same changes from mkdocstrings-python: https://github.com/mkdocstrings/python/commit/a9078a020e984f7d94e531644e613c08a5fc35ca

**Comment by pawamoy** [comment]
Fixed, still some chores to do and I'll release a new version.
