### ISSUE TITLE
bug: deprecation warning with latest mkdocstrings and autorefs

### ISSUE THREAD

**Issue by mschoettle** [mkdocstrings/python-legacy#6]
### Description of the bug

The following deprecation warning gets output with the latest mkdocstrings version:

https://github.com/mkdocstrings/autorefs/blob/40940c591e9cc557573ccd35351ca2b535ec371b/src/mkdocs_autorefs/references.py#L274-L279

I am aware that this is the legacy Python handler. Despite that, is there still interest in having this fixed?

**Comment by pawamoy** [comment]
Yes, this should be fixed! Thanks for reporting.

**Comment by mschoettle** [comment]
Great!

I tried replacing this here:

https://github.com/mkdocstrings/python-legacy/blob/c8aacd7815110321fe42971345718fa913ab427a/src/mkdocstrings_handlers/python/rendering.py#L28

with:

```py
return Markup("<autorefs optional-hover={path}>{brief}</autorefs>").format(path=path, brief=brief)
```

It fixes the warning, not sure if it's correct though. A quick comparison of some rendered output seems to be identical.

If that looks good I can create a PR.

**Comment by pawamoy** [comment]
It should be this:

```python
return Markup("<autoref identifier={path} optional hover>{brief}</autoref>").format(path=path, brief=brief)
```

PR welcome! I should be able to review+merge+release tomorrow :)
